# Generated by Django 4.2 on 2023-04-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, verbose_name='상품코드')),
                ('name', models.CharField(max_length=200, verbose_name='상품명')),
                ('description', models.TextField(max_length=256, verbose_name='상품설명')),
                ('price', models.IntegerField(max_length=32, verbose_name='상품가격')),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('F', 'Free')], max_length=1, verbose_name='상품사이즈')),
            ],
        ),
    ]
