# Generated by Django 4.2 on 2023-04-07 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '상품등록'},
        ),
        migrations.AlterModelTable(
            name='product',
            table='product create',
        ),
    ]
