# Generated by Django 4.2 on 2023-04-07 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_alter_product_options_alter_product_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '상품'},
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
