# Generated by Django 4.2 on 2023-04-07 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_alter_product_options_alter_product_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=32, verbose_name='상품명'),
        ),
    ]
