# Generated by Django 4.2 on 2023-04-07 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_alter_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inbound',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='erp.product')),
                ('quantity', models.IntegerField(max_length=32, verbose_name='상품수량')),
                ('inbound_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '입고',
                'db_table': 'inbound',
            },
            bases=('erp.product',),
        ),
    ]
