# Generated by Django 4.2 on 2023-04-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_inbound'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='상품가격'),
        ),
        migrations.DeleteModel(
            name='Inbound',
        ),
    ]
