# Generated by Django 4.2 on 2023-04-07 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_inbound'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbound',
            name='price',
        ),
    ]
