# Generated by Django 4.2 on 2023-04-09 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0009_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbound',
            name='inbound_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='입고날짜'),
        ),
        migrations.AlterField(
            model_name='inbound',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.product', verbose_name='상품코드'),
        ),
    ]
