# Generated by Django 4.2 on 2023-04-09 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0010_alter_inbound_inbound_date_alter_inbound_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='수량')),
                ('outbound_date', models.DateTimeField(auto_now_add=True, verbose_name='출고날짜')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.product', verbose_name='상품코드')),
            ],
            options={
                'verbose_name': '출고',
                'db_table': 'outbound',
            },
        ),
    ]
